### ISSUE TITLE
Missing ViolenceNet.ckpt

### ISSUE THREAD

**Issue by phatberstromgg** [hasnainnaeem/Violence-Detection-in-Videos#1]
Hi @hasnainnaeem, I am trying to train the data by following your instruction, I have met the problem when complied Train.py, it is said that there is no ViolenceNet.ckpt found. I search in your datalists folder and the file checkpoint seems to be cracked (1KB). Could you send me your .ckpt file? My email: phat.429429@gmail.com. Thank you.

**Comment by bilel-bj** [comment]
Thanks for the interesting work.
Could you provide the checkpoint file for download?

**Comment by Minpig** [comment]
Hi @hasnainnaeem,I also meet some questions when compiled Train.py.It is said that 
`Could not open /src/data/pretrainModels/darknet19/darknet19.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Could not open /src/data/pretrainModels/darknet19/darknet19.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2020-01-06 14:31:25.824405: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:172 : Data loss: Unable to open table file /src/data/pretrainModels/darknet19/darknet19.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /src/data/pretrainModels/darknet19/darknet19.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save_1/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[{{node save_1/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_140_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


Can you tell me how to solve the problem？？ My email:farjanayas89654@gmail.com
`

**Comment by hasnainnaeem** [comment]
Hello. Sorry for the delayed response. Here's the link to the checkpoint file for HockeyFight dataset:
https://drive.google.com/file/d/1TwGzBTooHvAkBcrKzEfukrZMSakuCdYd/view

**Comment by hasnainnaeem** [comment]
> Thanks for the interesting work.
> Could you provide the checkpoint file for download?

Thank you. This work was mainly done by @JoshuaPiinRueyPan. In case you face other issues, check issues listed in his repo for help over here:
https://github.com/JoshuaPiinRueyPan/ViolenceDetection/issues

Let me know if you need any further help.
