### ISSUE TITLE
Could you extend your project for multiple camera. Does it affect to performance?

### ISSUE THREAD

**Issue by phatberstromgg** [hasnainnaeem/Violence-Detection-in-Videos#2]
Hi @hasnainnaeem, I have ran your project and it is great. My question is could you extend your project for using multiple cameras, maybe 3, 4 or more. If can, how about the performance of it.

Thank you.
Best regards.

**Comment by hasnainnaeem** [comment]
Firstly, I am very late to respond, sorry about that.

I have not tried running using multiple cameras. It's definitely possible. It's originally Joshua's work (mentioned in README), that's why I can't provide deeper insights.
